### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'defaultFieldValues')

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts#148]
Intentando correr github.com/pdepjm/2020-o-tpi-juego-wolollok

```
alf@q2alf:~/repos/pdep/2020/objetos/2020-o-tpi-juego-wolollok (master u=)$ ./wollok-ts-cli-linux test
Running all tests on /home/alf/repos/pdep/2020/objetos/2020-o-tpi-juego-wolollok
Reading project files: 14.771ms
Building environment: 2.014s
/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:339
    (_a = node.defaultFieldValues()) === null || _a === void 0 ? void 0 : _a.forEach((value, field) => {
               ^

TypeError: Cannot read properties of undefined (reading 'defaultFieldValues')
    at getUninitializedAttributes (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:339:16)
    at getUninitializedAttributesForInstantation (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:334:12)
    at /snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:123:83
    at /snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:37:116
    at /snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:542:42
    at Array.map (<anonymous>)
    at /snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/validator.js:542:14
    at applyReduce (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/model.js:150:12)
    at /snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/model.js:149:20
    at Array.reduce (<anonymous>)

```

**Comment by fdodino** [comment]
El proyecto está definido con abstracciones viejas:

- usa `++`
- define `fixture` que ahora se reemplaza por `method initialize()`
- tiene definiciones duplicadas

Lo traté de emprolijar pero me está llevando mucho tiempo y me parece que el issue original ya no se da más (era sin dudas algún manejo de undefined que estaba flojo de papeles).

Les dejo acá el proyecto toqueteado (no lo pude pushear porque no tengo permisos): [2020-o-tpi-juego-wolollok.tar.gz](https://github.com/uqbar-project/wollok-ts/files/14984376/2020-o-tpi-juego-wolollok.tar.gz)

@asanzo @PalumboN , yo daría por cerrado el issue.

**Comment by PalumboN** [comment]
Además se hicieron varios cambios al código del validador desde entonces, lo cierro hasta que aparezca de nuevo :P
