### ISSUE TITLE
Capturar los errores del parser para generar un problem en el file

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#174]
Hoy cuando escribimos algo como

```wollok
program "77" {
  var nombre = 322
  
}
```

En el output de Wollok-LSP-IDE aparece

```bash
- PARSING FAILED --------------------------------------------------

> 1 | program "77" {
    |         ^
  2 |   var nombre = 322
  3 |   

Expected one of the following: 

comment, identifier, whitespace

    at /home/dodain/workspace/wollok-dev/wollok-lsp-ide/node_modules/wollok-ts/dist/index.js:50:19
    at Array.map (<anonymous>)
    at buildEnvironment (/home/dodain/workspace/wollok-dev/wollok-lsp-ide/node_modules/wollok-ts/dist/index.js:45:40)
    at /home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/out/utils/vm/environment-provider.js:39:53
    at EnvironmentProvider.changeEnvironment (/home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/out/utils/vm/environment-provider.js:47:28)
    at EnvironmentProvider.rebuildTextDocument (/home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/out/utils/vm/environment-provider.js:32:14)
    at /home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/out/server.js:62:25
    at CallbackList.invoke (/home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at /home/dodain/workspace/wollok-dev/wollok-lsp-ide/server/node_modules/vscode-languageserver/lib/common/textDocuments.js:138:42
```

yo creo que podría atraparse ese error y construirle un Problem al file. Hoy el LSP hace eso

```ts
export const validateTextDocument =
  (connection: Connection, allDocuments: TextDocument[]) =>
  (textDocument: TextDocument) =>
  async (environment: Environment): Promise<void> => {
    await updateDocumentSettings(connection)

    try {
      const timeMeasurer = new TimeMeasurer()
      const problems = validate(environment)
      timeMeasurer.addTime('build environment for file')

      sendDiagnostics(connection, problems, allDocuments)
      timeMeasurer.addTime('validation time')

      timeMeasurer.finalReport()
    } catch (e) {
      // TODO: Generate a high-level function
      const uri = wollokURI(textDocument.uri)
      const content = textDocument.getText()

      connection.sendDiagnostics({
        uri: uri,
        diagnostics: [
          createDiagnostic(textDocument, {
            level: 'error',
            code: 'FileCouldNotBeValidated',
            node: { sourceFileName: () => uri },
            values: [],
            sourceMap: {
              start: {
                line: 1,
                offset: 0,
              },
              end: {
                line: Number.MAX_VALUE,
                offset: content.length - 1,
              },
            },
          } as unknown as Problem),
        ],
      })
    }
  }
```

solo que está dentro de validateTextDocument y hay dos lugares donde se llama pero tira error antes y no lo puede atrapar:

```ts
documents.onDidChangeContent((change) => {
  environmentProvider.rebuildTextDocument(change.document)
  environmentProvider.withLatestEnvironment(
    validateTextDocument(connection, documents.all())(change.document),
  )
})

documents.onDidOpen((change) => {
  environmentProvider.rebuildTextDocument(change.document)
  environmentProvider.withLatestEnvironment(
    validateTextDocument(connection, documents.all())(change.document),
  )
})
```

de paso podríamos refactorizar ese código repetido.

Podría corregirlo en el LSP IDE pero me parece una mejor UX que lo haga wollok-ts... @PalumboN ?

**Comment by PalumboN** [comment]
Para mí hay que tocar el parser, y que deje un `malformedEntity`.

Ese `try-catch` del LSP está para que no se vaya todo a la mierda :P no debería haber lógica de dominio ahí.

**Comment by fdodino** [comment]
Coincido en que deje un `malformedEntity`, o sea, es responsabilidad del parser recuperarse del código roto de manera de no tirar excepción e indicar "hay un error de la línea 1 a la 80, es imposible parsear ésto". Por otro lado, yo creo que tenemos que poner un try/catch con código que no sea de negocio, sino simplemente de UI, de capturar esos errores para que no salte el popup abajo a la derecha de "TextDocument failed", y que muestre el error en la ventana de output, para mejorar la UX.

**Comment by fdodino** [comment]
Bueno, acabo de testearlo y ya está devolviendo un malformedEntity:
![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/f4d1d8a2-1197-4d87-bbe7-25d9aa21f954)

Lo que no entiendo es por qué en el sourceMap devuelve un caracter menos. Lo voy a investigar.
Por otra parte, hay otro issue que tengo que ver si Ivo ya lo resolvió que es que está saltando un popup, al menos la primera vez. Pero eso es para Wollok LSP IDE.

**Comment by fdodino** [comment]
El problema en realidad es que el parser está fallando... este test se rompe

```ts
    it('should recover from program parse error', () => {
      'class A {} program "77" {}'.should.be.parsedBy(parser)
        .recoveringFrom('malformedEntity', 12, 19)
        .into(new Package({
          fileName: 'foo.wlk',
          name: 'foo',
          members: [
            new Class({ name: 'A' }),
          ],
        }))
    })
```

Y pasa lo mismo con class, object si lo quiero definir con un nombre que tenga comillas dobles

**Comment by PalumboN** [comment]
Esto está relaacionado con https://github.com/uqbar-project/wollok-ts/issues/245

Hay que buscar una forma piola de que si intenta parsear un member particular falla, se recupere.
