### ISSUE TITLE
Asignacion recursiva

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-ts#195]
Al levantar un archivo con este contenido
```wlk
object pepita {
  var property energia = self.energia()
}
```

La vm rompe con este error
```
WollokException [wollok.lang.EvaluationError wrapping TypeScript TypeError]: Generator is already running
        at src.prueba.pepita.energia() [src/prueba.wlk:--]
        at Send [src/prueba.wlk:2]
     Derived from TypeScript stack
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:289:39)
    at exec.next (<anonymous>)
    at Evaluation.execReturn (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:353:50)
    at execReturn.next (<anonymous>)
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:269:51)
    at exec.next (<anonymous>)
    at Evaluation.execBody (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:336:34)
    at execBody.next (<anonymous>)
    at Evaluation.exec (/snapshot/wollok-ts-cli/node_modules/wollok-ts/dist/interpreter/runtimeModel.js:262:49)
    at exec.next (<anonymous>)
```

- Se podria validar esto estaticamente con una validation?
- Si no handlearlo para que tire un error mas lindo?

**Comment by fdodino** [comment]
@ivojawer @PalumboN 

Le agregué un validador al Field:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/bdf75578-5886-400c-89eb-1199825230fe)

Y ese mismo lo estoy aprovechando para el intérprete:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/b90844eb-8ba8-4709-af13-5792b332dd33)

**Comment by fdodino** [comment]
Me quedé con la duda de cómo se comportaba Xtext:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/3fb7da21-b39d-470d-a4d6-7d3bfbf03462)

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/fb2d6201-42dc-40b9-a30d-5b54c68375f7)

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/f7af43f0-bf16-45f0-81c2-8d8bdb39166d)
