### ISSUE TITLE
Problemas con el orden de inicialización

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#68]
Tengo este programa
```wollok

object o {
  var property x = pepita.energia() / 2
}

object pepita {
  var property energia

  method initialize() {
    energia = 2
  }
}

test "TEST" {
  assert.equals(1, o.x())
}
```

Que rompe con `Error: LOAD of missing local "energia" on context ...`

---------

Supongo que el problema es el orden en el que se crean e inicializan los singletons. Este mismo programa pero con la definición de lo objetos al revés (primero pepita) **funciona**.

**Comment by guillep** [comment]
On the master branch I can reproduce this problem too: with this order of definitions I get an error, inverting them makes it work. In the master branch however the stack trace looks slightly different:

```bash
/Users/guille/Projects/wollok-ts/src/interpreter.ts:213
        if (!this.currentFrame()) throw new Error(`Reached end of stack with unhandled exception ${JSON.stringify(exception)}`)
                                        ^
Error: Reached end of stack with unhandled exception {"moduleFQN":"wollok.lang.EvaluationError","id":"4ad84a80-0c22-4c79-809f-fb9e57abbf2b","innerValue":{}}
    at Evaluation.raise (/Users/guille/Projects/wollok-ts/src/interpreter.ts:213:41)
    at /Users/guille/Projects/wollok-ts/src/interpreter.ts:836:18
    at /Users/guille/Projects/wollok-ts/src/interpreter.ts:848:5
```

I'd say from the exception that the real exception is being masked?

**Comment by PalumboN** [comment]
@guillep Sí, hay que activar el [modo debug para los log](https://github.com/uqbar-project/wollok-ts/blob/2f4c6f49be37237574e872d303d343f297b56778/test/wtest.ts#L49) para ver la excepción real.

Igual esto ya lo pude solucionar en https://github.com/uqbar-project/wollok-ts/pull/75 (si querés chusmearlo), pero me quedó https://github.com/uqbar-project/wollok-ts/issues/74 como pendiente (que como se solucionó hace poco en la versión de xtext no es crítico para Wollok Game Web, por eso lo pateo).

**Comment by guillep** [comment]
> @guillep Sí, hay que activar el [modo debug para los log](https://github.com/uqbar-project/wollok-ts/blob/2f4c6f49be37237574e872d303d343f297b56778/test/wtest.ts#L49) para ver la excepción real.

No hay una wiki donde poner esa info? Porque viniendo de ajuera medio que eso esta escondido en un archivo en medio del source :).

Y otra, siendo que en el readme proponen usar code, no se pueden agregar en el repo algunos archivos de config de code que tengan ya algunas de estas opciones ON y OFF? Si no tenes que setupearte el ambiente cada vez...

**Comment by guillep** [comment]
> Y otra, siendo que en el readme proponen usar code, no se pueden agregar en el repo algunos archivos de config de code que tengan ya algunas de estas opciones ON y OFF? Si no tenes que setupearte el ambiente cada vez...

O hasta podrian estar en otro repo, no me importa, lo que sea mas barato.
